### ISSUE TITLE
Extend database schema to include `method_file`

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#559]
- [x] Add `method_file` column in `instrument_functions` and `sample_file`.
- [x] Add `instrument_function_id` in `sample_file` to reference `instrument_functions`
- [x] Update SQLAlchemy models, uncluding Sample view
- [x] Add to migration script setting instrument_function `method_file` based on its `datetime_utc`
- [ ] Write a migration script to populate `instrument_function_id` in `sample_file` -> moved to following issues #619
- [x] Update `get_instrument_functions`
- [x] Update pydantic models InstrumentFunctionCreateBody 
- [ ] ~Update `file-converter` to read and write `method_file`~ -> User input of method_file would be required when processing sample #619
- [ ] ~Update pydantic models SampleFileCreate~  -> Update endpoint will be used, moved to #619
